M48
; DRILL file {KiCad 8.0.1} date 2024-06-02T00:59:24+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-06-02T00:59:24+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X163.36Y-100.345
X163.36Y-106.125
T2
X149.683Y-108.159
M30
