M48
; DRILL file {KiCad 8.0.3} date 2024-06-25T22:30:52+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-06-25T22:30:52+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X118.583Y-82.304
X118.583Y-88.084
T2
X104.905Y-90.118
M30
