name: KiCad Jobset Automation

on: 
  workflow_dispatch:
  push:
    paths:
      - '**/*.kicad_pro'
      - '**/*.kicad_pcb'
      - '**/*.kicad_sch'

jobs:
  run-kicad-jobset:
    name: Run KiCad Jobset
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad:9.0
      options: --user root

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run KiCad CLI Jobset
      run: |
        mkdir output
        find . -name "*.kicad_pro" -exec \
          kicad-cli jobset run -f ./actions.kicad_jobset {} \;

    - name: Compress Output Folders
      run: |
        apt-get update && apt-get install -y zip
        cd output
        find * -maxdepth 0 -type d -print0 | while IFS= read -r -d '' dir; do
          zip -qr "${dir}.zip" "$dir"
        done

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kicad-zips
        path: output/*.zip